version: '3'
services:
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123
    mongo:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        command: mongod --smallfiles --logpath=/dev/null
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null

    php:
        build: containers/php-fpm
        ports:
            - '9007:9000'
        volumes:
            - ./frontend:/var/www/interfaces:consistent
        links:
            - mysql
    nginx:
        build: containers/nginx
        ports:
            - '8092:80'
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:consistent
            - ./frontend:/var/www/interfaces:consistent
